theme = "night_owl"

[editor]
auto-pairs = false
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "version-control"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
C-h = "move_char_left" # Move cursor left
C-j = "move_visual_line_down" # Move cursor down
C-k = "move_visual_line_up" # Move cursor up
C-l = "move_char_right" # move cursor right

[keys.normal]
C-s = ":w" # Save the current file
C-q = ":q" # Close the current file

# Move selected lines up/down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Copy the selected lines above/below
S-A-j = ["extend_to_line_bounds", "yank", "paste_after"]
S-A-down = ["extend_to_line_bounds", "yank", "paste_after"]
S-A-k = ["extend_to_line_bounds", "yank", "paste_before"]
S-A-up = ["extend_to_line_bounds", "yank", "paste_before"]
